apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
    - {{ kubernetes_api_name }}
  timeoutForControlPlane: 4m0s
controlPlaneEndpoint: {{ kubernetes_api_name }}:6443
networking:
  podSubnet: {{ kubernetes_pod_network_cidr }}
